apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fabric-zk-kafka
  name: kafka1
spec:
  replicas: 1
  template:
    metadata:
      labels:
       app: hyperledger
       role: kafka
       kafka-id: kafka1
    spec:
      containers:
        - name: kafka1
          image: hyperledger/fabric-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper0:2181,zookeeper1:2181,zookeeper2:2181"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "103809024"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "103809024"
            - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
              value: "false"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka1.fabric-zk-kafka"
---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric-zk-kafka
   name: kafka1
spec:
 selector:
   app: hyperledger
   role: kafka
   kafka-id: kafka1
 clusterIP: None
 ports:
   - name: kafka-port1
     protocol: TCP
     port: 9092

   - name: kafka-port2
     protocol: TCP
     port: 9093