apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fabric-zk-kafka
  name: kafka3
spec:
  replicas: 1
  template:
    metadata:
      labels:
       app: hyperledger
       role: kafka
       kafka-id: kafka3
       ns: fabric-zk-kafka
    spec:
      containers:
        - name: kafka3-kafka
          image: hyperledger/fabric-kafka:x86_64-1.0.4
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper0.fabric-zk-kafka:2181,zookeeper1.fabric-zk-kafka:2181,zookeeper2.fabric-zk-kafka:2181"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "103809024"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "103809024"
            - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
              value: "false"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka3.fabric-zk-kafka"
---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric-zk-kafka
   name: kafka3
spec:
 selector:
   app: hyperledger
   role: kafka
   kafka-id: kafka3
   ns: fabric-zk-kafka
 clusterIP: None
 ports:
   - name: kafka-port1
     protocol: TCP
     port: 9092

   - name: kafka-port2
     protocol: TCP
     port: 9093
---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric-zk-kafka
   name: kafka3-ex
spec:
 selector:
   app: hyperledger
   role: kafka
   kafka-id: kafka3
   ns: fabric-zk-kafka
 type: NodePort
 ports:
   - name: kafka-port1
     protocol: TCP
     port: 9092
     targetPort: 9092
     nodePort: 32737

   - name: kafka-port2
     protocol: TCP
     port: 9093
     targetPort: 9093
     nodePort: 32738