apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fabric-zk-kafka
  name: kafka2
spec:
  replicas: 1
  template:
    metadata:
      labels:
       app: hyperledger
       role: kafka
       kafka-id: kafka2
    spec:
      containers:
        - name: kafka2
          image: hyperledger/fabric-kafka
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper0:2181,zookeeper1:2181,zookeeper2:2181"
---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric-zk-kafka
   name: kafka2
spec:
 selector:
   app: hyperledger
   role: kafka
   kafka-id: kafka2
 clusterIP: None
 ports:
   - name: kafka-port1
     protocol: TCP
     port: 9092

   - name: kafka-port2
     protocol: TCP
     port: 9093