apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fabric-zk-kafka
  name: zookeeper2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
       app: hyperledger
       role: zookeeper
       zookeeper-id: zookeeper2
       ns: fabric-zk-kafka
    spec:
      containers:
        - name: zookeeper2
          image: hyperledger/fabric-zookeeper:latest
          env:
            - name: ZOO_MY_ID
              value: "3"
            - name: ZOO_SERVERS
              value: "server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=0.0.0.0:2888:3888"
            - name: ZOO_TICK_TIME
              value: "2000"
            - name: ZOO_INIT_LIMIT
              value: "10"
            - name: ZOO_SYNC_LIMIT
              value: "2"
---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric-zk-kafka
   name: zookeeper2
spec:
 selector:
   app: hyperledger
   role: zookeeper
   zookeeper-id: zookeeper2
   ns: fabric-zk-kafka
 clusterIP: None

 ports:
   - name: zookeeper-port1
     protocol: TCP
     port: 2888

   - name: zookeeper-port2
     protocol: TCP
     port: 3888

   - name: zookeeper-port3
     protocol: TCP
     port: 2181